# Default values for spring-boot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
image:
  registry: "docker.io"
  name: "davilson18/springboot-demo"
  version: "latest"
  pullPolicy: Always

imagePullSecrets: []
command: []
args: []
extraArgs: []
extraEnv: []
ports: []
volumes: []
volumeMounts: []
persistentVolume: 
  enabled: false
healthCheck:
  enabled: false
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 2
    tcpSocket:
      port: 8080
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 2
    tcpSocket:
      port: 8080

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext: 
  privileged: true

resources: 
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 128Mi
    
replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## Kubernetes svc configuration
##
service:
  type: NodePort
  loadBalancerIP: ""
  externalTrafficPolicy: Cluster
  ports:
    http:
      port: 8080
      protocol: TCP
      nodePort: 30020
  loadBalancerSourceRanges: []
  clusterIP: ""
  annotations: {}